### ISSUE TITLE
Crash when using Galacticraft's Compressor

### ISSUE THREAD

**Issue by Flactine** [GotoLink/RecipeHandler#18]
When right-click the Galacticraft's Compressor with NoMoreRecipeConflict mod, game crashed.

**Comment by Jacky10X** [comment]
@GotoLink i also have this problem when i try to use Galacticraft's Compressor
 (it happen to me when you have thaumcraft , Galacticraft and no more recipe conflict)
https://pastebin.com/SCwc9g9i

**Comment by GotoLink** [comment]
@Jacky10X Your issue is #17, Thaumcraft based. Supposedly solve in Azanor/thaumcraft-beta#502.

**Comment by Jacky10X** [comment]
@GotoLink 
No When you have three of them it will crash no matter what( i have try it, All version is lastest)
I have ask the Galacticraft and they explain your mod cause the problem

https://github.com/micdoodle8/Galacticraft/issues/3402

**Comment by MachinegunMarty** [comment]
Can confirm that this happens with:

Forge1.12.2-2707 +
Thaumcraft1.12.2-6.1-BETA16 +
NoMoreRecipeConflict-0.10(1.12.2) +
GalacticraftCore-1.12.2-4.0.1.177
( +VanillaFix-1.0.8-88)

Placed the compressor to start Galacticraft and that crashed my client.
VanillaFix crash screen said 3 mods are responsible: Thaumcraft, Galacticraft and nomorerecipeconflict.

[main/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1486) ~[buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3934) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 9
	at java.util.Arrays$ArrayList.get(Arrays.java:3841) ~[?:1.8.0_172]
	at net.minecraft.util.NonNullList.get(SourceFile:44) ~[fi.class:?]
	at micdoodle8.mods.galacticraft.core.inventory.PersistantInventoryCrafting.getStackInSlot(PersistantInventoryCrafting.java:41) ~[PersistantInventoryCrafting.class:?]
	at thaumcraft.api.crafting.ShapelessArcaneRecipe.matches(ShapelessArcaneRecipe.java:59) ~[ShapelessArcaneRecipe.class:?]
	at assets.recipehandler.CraftingHandler.getCrafts(CraftingHandler.java:175) ~[CraftingHandler.class:?]
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:263) ~[CraftingHandler.class:?]
	at assets.recipehandler.GuiEventHandler$CreativeButton.drawButton(GuiEventHandler.java:130) ~[GuiEventHandler$CreativeButton.class:?]
	at net.minecraft.client.gui.GuiScreen.drawScreen(GuiScreen.java:70) ~[blk.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:80) ~[bmg.class:?]
	at micdoodle8.mods.galacticraft.core.client.gui.container.GuiContainerGC.drawScreen(GuiContainerGC.java:28) ~[GuiContainerGC.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at Reflector.callVoid(Reflector.java:648) ~[Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456) ~[buq.class:?]
	... 9 more


[2018-06-16-4.log](https://github.com/GotoLink/RecipeHandler/files/2108163/2018-06-16-4.log)

I attached my full log. Hope it helps you locate the problem.

The client crash didn't affect my server.

I tried with the normal Compressor and with the Electrical Compressor and both crash the client.
Just place one down and right click it and .... crash. 
After the crash i can't re-enter the game. I have to fully shutdown my client and then restart the client.
After the restart i can enter the game again, but if i right click the compressor again... crash.

I hope the info and log help you to locate the problem. 
Good luck and thanx in advance !

grtz,

MachinegunMarty

**Comment by GotoLink** [comment]
Yes that is the thaumcraft issue with its recipe not checking the inventory space before fetching the content.
Try update Thaumcraft ? The author said he fixed it.

**Comment by Jacky10X** [comment]
@GotoLink But the problem is your mod not the thaumcraft
because of these reasons
(a) trying to draw a button which shouldn't be there as our machine is not a standard Crafting Table;
(b) then accessing Thaumcraft recipes which are larger than 3 x 3 inside our Compressor which (like a regular Crafting Table) only has a 3 x 3 crafting grid. It's these "larger than 3x3" recipes which are causing NoMoreRecipeConflict to crash.
It is said by Galacticraft authors you can check it
This is not the thaumcraft problem

and the main problem is some crafting recipe is larger than 3x3 but the compressor only have 3 x 3 (it shouldn't be happen because you can't craft something crafting recipe is larger than 3x3 in 3 x 3 crafting grid )
So maybe you can detect is it galactic craft items when using the items/blocks, if it is then no more recipe conflict don't do anything about these items/blocks

**Comment by GotoLink** [comment]
As i said before, the recipe is at fault, since shapeless recipes are responsible for checking the crafting grid.
It is consistent with the fact it crashes the same with various crafting blocks.
I'll push it onto Thaumcraft issue report, since you are using latest version and the issue isn't fixed.

Anyhow, if Galacticraft compressor needs to be removed from crafting conflict support, you can do so by adding in recipehandler.cfg file, under "Black List Crafting Container" option: micdoodle8.mods.galacticraft.core.inventory.ContainerElectricIngotCompressor

**Comment by MachinegunMarty** [comment]
Hi GotoLink,

We are indeed using the latest version of thaumcraft (beta16 as of writing) and there is no newer release. Same goes for Galacticraft 177.

I tried your suggestion by adding that line to my client and server recipehandler.cfg and it still crashes the client.
I tried it with the compressor and Electric Compressor, both crashed the client.

java.lang.ArrayIndexOutOfBoundsException: 9
    at java.util.Arrays$ArrayList.get(Arrays.java:3841)
    at net.minecraft.util.NonNullList.get(SourceFile:44)
    at micdoodle8.mods.galacticraft.core.inventory.PersistantInventoryCrafting.getStackInSlot(PersistantInventoryCrafting.java:41)
    at thaumcraft.api.crafting.ShapelessArcaneRecipe.matches(ShapelessArcaneRecipe.java:59)
    at assets.recipehandler.CraftingHandler.getCrafts(CraftingHandler.java:175)
    at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:263)
    at assets.recipehandler.GuiEventHandler$CreativeButton.drawButton(GuiEventHandler.java:130)
    at net.minecraft.client.gui.GuiScreen.drawScreen(GuiScreen.java:70)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:80)
    at micdoodle8.mods.galacticraft.core.client.gui.container.GuiContainerGC.drawScreen(GuiContainerGC.java:28)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
    at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at Reflector.callVoid(Reflector.java:648)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3934)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[latest.log](https://github.com/GotoLink/RecipeHandler/files/2109042/latest.log)

Latest client log attached.

Again not blaming any of the mods, just trying to find a solution and make the mod makers aware of the issue. 
This seems to be the post containing the most information allready about the problem, so i'll keep updating this GitHub and link the other mod makers to this hub.

Doesn't seem to be your mod anymore however, because I now blocked out the compressor crafting grid interaction completely with your line in the cfg, and it still happens.

Hope this helps tho finding the problem.

If i can do anything to help, just ask.

grtz,

MachinegunMarty

**Comment by Jacky10X** [comment]
@GotoLink Oh then i apologize because i thought it was your mod fault and i don't know it is also other mod crafting recipe problem 
i hope this problem can be fixed 
because these three of the mod is really awesome and i can't really lack one of them

**Comment by radfast** [comment]
Hey guys, Galacticraft author here.  Although our Compressor machine is triggering this issue, it's **not** our code _causing_ it, it's just another example of #17 which is an interaction between this mod and Thaumcraft.

Anyhow I think **Thaumcraft** have now made a change to fix this, or will in next version - see post by @Azanor [here](https://github.com/Azanor/thaumcraft-beta/issues/502#issuecomment-398681322)

**Comment by GotoLink** [comment]
Fixed, according to Thaumcraft B17 changelog and github issue.
